name: deploy

on:
  push:
    branches:
      - '**' # matches every branch
      - '!main'
  pull_request:
    branches:
      - 'main'
    types: [opened]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set env.BRANCH
        run: echo "IS_MAIN_BRANCH=${{ (github.ref_name == 'main') }}" >> $GITHUB_ENV
      -
        name: Build image
        uses: docker/build-push-action@v4
        with:
          context: .
          # platforms: linux/amd64,linux/arm64
          platforms: linux/amd64
          push: ${{ env.IS_MAIN_BRANCH }}
          tags: kinoba/javascript-static-code-analyzer:latest