name: deploy

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    uses: Kinoba/javascript-static-code-analyzer-dockerized/.github/workflows/build.yml@main
  
  push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: kinoba/javascript-static-code-analyzer:latest